<?xml version="1.0" encoding="UTF-8" ?>
<!-- A schema importing another one which defines a different type with the same
     local name ("itemType"), as happens when combining schemas from different
     sources in a single document. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:m="http://www.cre.fr/xml2db/main"
           xmlns:o="http://www.cre.fr/xml2db/other"
           targetNamespace="http://www.cre.fr/xml2db/main"
           elementFormDefault="qualified">

    <xs:import schemaLocation="other.xsd" namespace="http://www.cre.fr/xml2db/other"/>

    <xs:element name="basket" type="m:basketType"/>

    <xs:complexType name="basketType">
        <xs:sequence>
            <xs:element name="reference" type="xs:string"/>
            <xs:element name="item" type="m:itemType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="itemType">
        <xs:sequence>
            <xs:element name="label" type="xs:string"/>
            <xs:element ref="o:item" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>
