name: MySQL integration tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    container: python:3.11-bookworm
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Start MySQL
        run: |
          /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 .[tests] pymysql
    
      - name: Test with pytest
        run: |
          pytest tests
        env:
          DB_STRING: mysql+pymysql://root:root@localhost/test_db?charset=utf8mb4
